### ISSUE TITLE
not a rat

### ISSUE THREAD

**Issue by AppleiLev5s** [quivings/Solara#27]
basically it tries launching as normal, all av's off, but it just doesnt launch the main executor

**Comment by Danilmikhan** [comment]
its not confirmed to be one but it may be

**Comment by Danilmikhan** [comment]
its 100% a rat

**Comment by hnrie** [comment]
> its 100% a rat

Bro that's the solara server that got fucking hijacked and put up a FAKE solara that is a virus they spoke about this on the roblox hackers reddit and stuff so... maybe stop saying it's a rat then unless your from that server tryna get people to join it so you can then rip their shit in which case your a bozo

**Comment by Danilmikhan** [comment]
bluddy can't grow up 💀💀💀

**Comment by AppleiLev5s** [comment]
im gonna keep this issue open so people can see it

**Comment by Danilmikhan** [comment]
Proof?

**Comment by Danilmikhan** [comment]
I actually tested it in Triage, a free virtual machine that is used to check files and Solara is not a rat

**Comment by AppleiLev5s** [comment]
but can YOU prove its not a rat? SO MANY REPORTS of accounts STOLEN all from germany

**Comment by Danilmikhan** [comment]
bluddy cant read

**Comment by Danilmikhan** [comment]
and plus, qui already made so much proof that its not a rat

**Comment by Danilmikhan** [comment]
> but can YOU prove its not a rat? SO MANY REPORTS of accounts STOLEN all from germany

and also, proof?

**Comment by Danilmikhan** [comment]
lol bluddy changed his mind rq

**Comment by hnrie** [comment]
i was mean that too, haha

Vào Th 6, 14 thg 6, 2024 vào lúc 21:32 Danilmikhan <
***@***.***> đã viết:

**Comment by hnrie** [comment]
> but can YOU prove its not a rat? SO MANY REPORTS of accounts STOLEN all from germany
hey, go to this link [issue] and see the history for image proof https://github.com/quivings/Solara/issues/30
