### ISSUE TITLE
Bootstrapper is not working.

### ISSUE THREAD

**Issue by MonoShootGunner** [quivings/Solara#3]
It makes some folders inside the Solara folder, but it does not launch solara itself?
![image](https://github.com/quivings/Solara/assets/170293668/a0e571c8-0d37-4186-bc0d-e08e64f4aaed)

**Comment by qqwizzixxxx** [comment]
same thing

**Comment by korevar** [comment]
![image](https://github.com/quivings/Solara/assets/125364378/3b9167f6-04cf-4a8f-9fe8-67f7020df76b)
Вот здесь и ошибочка нашего дорого qui который даже не защищает свой чит. 
![image](https://github.com/quivings/Solara/assets/125364378/ba52fcc0-2b01-472b-b9bc-d44a23fa8154)

**Comment by korevar** [comment]
Well, what do you tell us qui?

**Comment by korevar** [comment]
of course you wrote on your knee. LET'S UPDATE THE UI AND THEN RETURN THE OLD VERSION OF THE UI AND BEFORE PROTECTING AND IMPROVING THE COMPATIBILITY OF MY CHEATS

**Comment by korevar** [comment]
> It makes some folders inside the Solara folder, but it does not launch solara itself? ![image](https://private-user-images.githubusercontent.com/170293668/331943769-a0e571c8-0d37-4186-bc0d-e08e64f4aaed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODg2NzQsIm5iZiI6MTcxNjI4ODM3NCwicGF0aCI6Ii8xNzAyOTM2NjgvMzMxOTQzNzY5LWEwZTU3MWM4LTBkMzctNDE4Ni1iYzBkLWUwOGU2NGY0YWFlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxMDQ2MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGQ5MDkzZjUyNzYzNTQwMzgyYjFhYmVhMzg3YjVjZDFmNzI5MjQ0YzEzNGZiOWE0MmJmZTNhY2M1MjZhMjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.__NcO-_VjyE1curKLIKhf84jI9mt543tItSnfEmXyUo)

Мужик, забрось ты нахуй эту темку.

**Comment by quivings** [comment]
Pushed an update to resolve the parsing error
