### ISSUE TITLE
`getscriptbytecode` returns empty string

### ISSUE THREAD

**Issue by Stefanuk12** [quivings/Solara#31]
pls fix

**Comment by Danilmikhan** [comment]
bro solara is a RAT you are dead

**Comment by hnrie** [comment]
> bro solara is a RAT you are dead

a LIAR, GET OUT! UR A LIAR

**Comment by hnrie** [comment]
> pls fix

contact qui

**Comment by hnrie** [comment]
> bro solara is a RAT you are dead

proof? and every executor have a false positive

**Comment by Stefanuk12** [comment]
ok ty for fix
