### ISSUE TITLE
There appears to be a good virus

### ISSUE THREAD

**Issue by scar17off** [quivings/Solara#6]
I discovered that there was a potential security threat in the file you provided, but I was able to address it before any harm was done. 

[Files from repo](https://www.virustotal.com/graph/embed/g5867ec3c788b4e4098c478daf5d6f50d02c3763345c144a593669e3aea787d8b?theme=dark)
[Bootstrap file](https://www.virustotal.com/graph/embed/g71867676129248a8a589dcd8b7399314f3a062fb31454c0983d977a6f18c054c?theme=dark)

Your executor contains intriguing requests to ip-api.com and ipinfo.io. Additionally, there are suspicious requests present that may indicate the presence of a token grabber or TikTok checker. Special thanks to [Laix3](https://www.virustotal.com/gui/user/Laix3) for thoroughly reviewing the activity within the file.

Thank you for your cooperation. Please refrain from sharing any harmful files.

**Comment by quivings** [comment]
Wowee what a yap sesh

**Comment by scar17off** [comment]
> Wowee what a yap sesh

I just wanted to make sure that your files are safe for people to download and use. If you have any questions or concerns about the security issue I mentioned, I'm happy to talk about it more.

**Comment by scar17off** [comment]
Could you please confirm if this is the website where the logo originated from?
I found that the icon is labeled as "zenith-service-company-business-5b00cd394f53e9.4955940715267791933249-20-1--20-1-.png".

![Снимок экрана 2024-05-23 104322](https://github.com/quivings/Solara/assets/81940406/a6f7f9b6-aa1c-4917-84de-4b2607dae5c5)

Next time, please remember to include a link to the website where you sourced the icons to avoid any potential copyright issues. Thank you.
